spring:
  datasource:
    url: jdbc:mysql://api.prism-sfa-dev.net:3306/sfa_db
    username: PrismSfa
    password: TestUser123!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false

  application:
    name: order-service

server:
  port: 9092
  servlet:
    context-path: /order-service

application:
  config:
    trace: true
