#DB_USERNAME: PrismSfa
#DB_URL: jdbc:mysql://api.prism-sfa-dev.net:3306/sfa_db
#DB_PASSWORD: TestUser123!
DB_USERNAME: root
DB_URL: jdbc:mysql://localhost:3306/pro_order
DB_PASSWORD: root
REST_URI: /api
SERVER:
  PORT: 9092
  servlet:
    context-path: /order-service