spring:
  datasource:
#    url: jdbc:mysql://prismgate.in:3306/gate_db
#    username: PrismGate
#    password: TestUser123!
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: order-service

server:
  port: 9093
  servlet:
    context-path: /order-service

spring-doc:
  swagger-ui:
    path: /swagger-ui-custom.html